using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using AutoSettings.Sdk;

namespace AutoSettings.DocGen;

/// <summary>
/// Builds the plugin SDK API reference (docs/plugins/api) from the public types of AutoSettings.Sdk and their XML
/// documentation, so the reference always matches the SDK.
/// </summary>
public static partial class ApiReferenceGenerator
{
    private const string Banner = "<!-- Generated by AutoSettings.DocGen from the AutoSettings.Sdk XML documentation. Do not edit by hand: run `dotnet run --project src/AutoSettings.DocGen`. -->";

    /// <summary>Returns relative path (inside docs/plugins/api) → content.</summary>
    public static SortedDictionary<string, string> Generate()
    {
        var assembly = typeof(IPlugin).Assembly;
        var docs = LoadDocs(assembly);
        var types = assembly.GetExportedTypes().OrderBy(t => t.Name, StringComparer.Ordinal).ToList();
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal) { ["index.md"] = Index(types, docs) };
        foreach (var type in types)
            files[$"{type.Name}.md"] = TypePage(type, docs, types);
        return files;
    }

    private static Dictionary<string, XElement> LoadDocs(Assembly assembly)
    {
        var path = Path.ChangeExtension(assembly.Location, ".xml");
        if (!File.Exists(path))
            throw new FileNotFoundException($"The XML documentation of {assembly.GetName().Name} was not found next to it ({path}).");
        return XDocument.Load(path).Descendants("member")
            .Where(m => m.Attribute("name") is not null)
            .ToDictionary(m => m.Attribute("name")!.Value, m => m, StringComparer.Ordinal);
    }

    private static string Index(List<Type> types, Dictionary<string, XElement> docs)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Banner).AppendLine();
        sb.AppendLine("# SDK API reference").AppendLine();
        sb.AppendLine($"Every public type of `AutoSettings.Sdk` {SdkInfo.Version} (namespace `AutoSettings.Sdk`). Start with");
        sb.AppendLine("[Writing a .NET plugin](../dotnet-plugins.md) for how they fit together.").AppendLine();
        foreach (var (title, filter) in Groups)
        {
            var group = types.Where(filter).ToList();
            if (group.Count == 0)
                continue;
            sb.AppendLine($"## {title}").AppendLine();
            sb.AppendLine("| Type | Description |").AppendLine("|---|---|");
            foreach (var type in group)
                sb.AppendLine($"| [`{DisplayName(type)}`]({type.Name}.md) | {Cell(Summary(docs, "T:" + type.FullName, types))} |");
            sb.AppendLine();
        }
        return Finish(sb);
    }

    private static readonly (string Title, Func<Type, bool> Filter)[] Groups =
    [
        ("Interfaces you implement", t => t.IsInterface && t.Name is "IPlugin" or "IPluginAction" or "IRevertiblePluginAction" or "IPluginCondition" or "IPluginTrigger"),
        ("Interfaces AutoSettings gives you", t => t.IsInterface && t.Name is not ("IPlugin" or "IPluginAction" or "IRevertiblePluginAction" or "IPluginCondition" or "IPluginTrigger")),
        ("Attributes", t => typeof(Attribute).IsAssignableFrom(t)),
        ("Enums", t => t.IsEnum),
        ("Classes and records", t => !t.IsInterface && !t.IsEnum && !typeof(Attribute).IsAssignableFrom(t)),
    ];

    private static string TypePage(Type type, Dictionary<string, XElement> docs, List<Type> types)
    {
        var sb = new StringBuilder();
        var id = "T:" + type.FullName;
        sb.AppendLine(Banner).AppendLine();
        sb.AppendLine($"# {DisplayName(type)}").AppendLine();
        sb.AppendLine($"Namespace `{type.Namespace}` · {KindName(type)}").AppendLine();
        sb.AppendLine("```csharp").AppendLine(Declaration(type)).AppendLine("```").AppendLine();
        AppendDoc(sb, docs, id, types);

        if (type.IsEnum)
        {
            sb.AppendLine("## Values").AppendLine();
            sb.AppendLine("| Value | Description |").AppendLine("|---|---|");
            foreach (var name in Enum.GetNames(type))
                sb.AppendLine($"| `{name}` | {Cell(Summary(docs, $"F:{type.FullName}.{name}", types))} |");
            sb.AppendLine();
            return Finish(sb);
        }

        const BindingFlags flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;
        var constructors = type.IsInterface || type.IsAbstract && type.IsSealed ? [] : type.GetConstructors(BindingFlags.Public | BindingFlags.Instance);
        var fields = type.GetFields(flags).Where(f => !f.IsSpecialName).OrderBy(f => f.Name, StringComparer.Ordinal).ToList();
        var properties = type.GetProperties(flags).Where(p => !IsCompilerGenerated(p)).OrderBy(p => p.Name, StringComparer.Ordinal).ToList();
        var methods = type.GetMethods(flags)
            .Where(m => !m.IsSpecialName && !IsCompilerGenerated(m) && !IsRecordPlumbing(type, m))
            .OrderBy(m => m.Name, StringComparer.Ordinal).ThenBy(m => m.GetParameters().Length).ToList();

        if (constructors.Length > 0 && !(IsRecord(type) && constructors.All(c => c.GetParameters().Length == 1 && c.GetParameters()[0].ParameterType == type)))
        {
            sb.AppendLine("## Constructors").AppendLine();
            foreach (var constructor in constructors.Where(c => !(IsRecord(type) && c.GetParameters().Length == 1 && c.GetParameters()[0].ParameterType == type)))
            {
                sb.AppendLine("```csharp").AppendLine($"public {Plain(type.Name)}({ParameterList(constructor)})").AppendLine("```").AppendLine();
                AppendDoc(sb, docs, MemberId(constructor), types);
            }
        }
        if (fields.Count > 0)
        {
            sb.AppendLine("## Constants").AppendLine();
            foreach (var field in fields)
            {
                var value = field.IsLiteral ? $" = {Literal(field.GetRawConstantValue())}" : "";
                sb.AppendLine($"### {field.Name}").AppendLine();
                sb.AppendLine("```csharp").AppendLine($"public {(field.IsLiteral ? "const" : "static readonly")} {TypeName(field.FieldType)} {field.Name}{value};").AppendLine("```").AppendLine();
                AppendDoc(sb, docs, $"F:{type.FullName}.{field.Name}", types);
            }
        }
        if (properties.Count > 0)
        {
            sb.AppendLine("## Properties").AppendLine();
            var nullability = new NullabilityInfoContext();
            foreach (var property in properties)
            {
                var accessors = property.SetMethod is { IsPublic: true } set
                    ? (set.ReturnParameter.GetRequiredCustomModifiers().Any(m => m.Name == "IsExternalInit") ? "get; init;" : "get; set;")
                    : "get;";
                var isStatic = property.GetMethod?.IsStatic == true ? "static " : "";
                sb.AppendLine($"### {property.Name}").AppendLine();
                sb.AppendLine("```csharp").AppendLine($"{(type.IsInterface ? "" : "public ")}{isStatic}{TypeName(property.PropertyType, nullability.Create(property))} {property.Name} {{ {accessors} }}").AppendLine("```").AppendLine();
                AppendDoc(sb, docs, $"P:{type.FullName}.{property.Name}", types);
            }
        }
        if (methods.Count > 0)
        {
            sb.AppendLine("## Methods").AppendLine();
            var nullability = new NullabilityInfoContext();
            foreach (var method in methods)
            {
                var modifiers = type.IsInterface ? "" : "public " + (method.IsStatic ? "static " : "");
                sb.AppendLine($"### {method.Name}").AppendLine();
                sb.AppendLine("```csharp").AppendLine($"{modifiers}{TypeName(method.ReturnType, nullability.Create(method.ReturnParameter))} {method.Name}({ParameterList(method)})").AppendLine("```").AppendLine();
                AppendDoc(sb, docs, MemberId(method), types);
            }
        }
        return Finish(sb);
    }

    private static void AppendDoc(StringBuilder sb, Dictionary<string, XElement> docs, string id, List<Type> types)
    {
        if (!docs.TryGetValue(id, out var member))
            return;
        if (member.Element("summary") is { } summary)
            sb.AppendLine(Markdown(summary, types)).AppendLine();
        var parameters = member.Elements("param").ToList();
        if (parameters.Count > 0)
        {
            sb.AppendLine("| Parameter | Description |").AppendLine("|---|---|");
            foreach (var parameter in parameters)
                sb.AppendLine($"| `{parameter.Attribute("name")?.Value}` | {Cell(Markdown(parameter, types))} |");
            sb.AppendLine();
        }
        if (member.Element("returns") is { } returns)
            sb.AppendLine("**Returns:** " + Markdown(returns, types)).AppendLine();
        foreach (var exception in member.Elements("exception"))
            sb.AppendLine($"**Throws** `{ShortCref(exception.Attribute("cref")?.Value)}`: {Markdown(exception, types)}").AppendLine();
        if (member.Element("remarks") is { } remarks)
            sb.AppendLine(Markdown(remarks, types)).AppendLine();
        if (member.Element("example") is { } example)
            sb.AppendLine("**Example**").AppendLine().AppendLine(Markdown(example, types)).AppendLine();
    }

    private static string Summary(Dictionary<string, XElement> docs, string id, List<Type> types) =>
        docs.TryGetValue(id, out var member) && member.Element("summary") is { } summary ? Markdown(summary, types) : "";

    /// <summary>Turns an XML documentation element into Markdown.</summary>
    private static string Markdown(XElement element, List<Type> types)
    {
        var sb = new StringBuilder();
        foreach (var node in element.Nodes())
            Append(sb, node, types);
        // Collapse the indentation of the XML into paragraphs.
        var text = sb.ToString();
        var parts = text.Split("\u0001");
        for (var i = 0; i < parts.Length; i += 2)
            parts[i] = Spaces().Replace(parts[i], " ").Replace(" \n", "\n").Replace("\n ", "\n");
        return string.Concat(parts).Trim();
    }

    private static void Append(StringBuilder sb, XNode node, List<Type> types)
    {
        switch (node)
        {
            case XText text:
                sb.Append(text.Value.Replace('\n', ' ').Replace('\r', ' '));
                break;
            case XElement { Name.LocalName: "c" } c:
                sb.Append('`').Append(c.Value).Append('`');
                break;
            case XElement { Name.LocalName: "code" } code:
                // \u0001 protects the code block from whitespace folding.
                sb.Append("\n\n\u0001```csharp\n").Append(Dedent(code.Value)).Append("\n```\u0001\n\n");
                break;
            case XElement { Name.LocalName: "para" } para:
                sb.Append("\n\n");
                foreach (var child in para.Nodes())
                    Append(sb, child, types);
                sb.Append("\n\n");
                break;
            case XElement { Name.LocalName: "see" or "seealso" } see when see.Attribute("cref") is { } cref:
                sb.Append(Link(cref.Value, types));
                break;
            case XElement { Name.LocalName: "see" } see when see.Attribute("langword") is { } word:
                sb.Append('`').Append(word.Value).Append('`');
                break;
            case XElement { Name.LocalName: "paramref" or "typeparamref" } reference:
                sb.Append('`').Append(reference.Attribute("name")?.Value).Append('`');
                break;
            case XElement { Name.LocalName: "list" } list:
                sb.Append("\n\n");
                foreach (var item in list.Elements("item"))
                {
                    sb.Append("\n- ");
                    foreach (var child in (item.Element("description") ?? item).Nodes())
                        Append(sb, child, types);
                }
                sb.Append("\n\n");
                break;
            case XElement other:
                foreach (var child in other.Nodes())
                    Append(sb, child, types);
                break;
        }
    }

    private static string Link(string cref, List<Type> types)
    {
        var name = cref[2..];
        var typeName = cref.StartsWith("T:", StringComparison.Ordinal) ? name : name[..Math.Max(0, (name.Contains('(') ? name[..name.IndexOf('(')] : name).LastIndexOf('.'))];
        var type = types.FirstOrDefault(t => t.FullName == typeName);
        var label = ShortCref(cref);
        if (type is null)
            return $"`{label}`";
        var anchor = cref.StartsWith("T:", StringComparison.Ordinal) ? "" : "#" + label[(label.LastIndexOf('.') + 1)..].ToLowerInvariant();
        return $"[`{label}`]({type.Name}.md{anchor})";
    }

    private static string ShortCref(string? cref)
    {
        if (cref is null)
            return "";
        var name = cref.Length > 2 && cref[1] == ':' ? cref[2..] : cref;
        if (name.Contains('('))
            name = name[..name.IndexOf('(')];
        name = name.Replace("AutoSettings.Sdk.", "").Replace("System.", "");
        return name.Replace("#ctor", "constructor");
    }

    private static string Dedent(string code)
    {
        var lines = code.Replace("\r\n", "\n").Trim('\n').Split('\n');
        var indent = lines.Where(l => l.Trim().Length > 0).Select(l => l.Length - l.TrimStart().Length).DefaultIfEmpty(0).Min();
        return string.Join("\n", lines.Select(l => l.Length >= indent ? l[indent..] : l.TrimStart())).TrimEnd();
    }

    private static string MemberId(MethodBase method)
    {
        var name = method is ConstructorInfo ? "#ctor" : method.Name;
        var parameters = method.GetParameters();
        var list = parameters.Length == 0 ? "" : "(" + string.Join(",", parameters.Select(p => XmlTypeName(p.ParameterType))) + ")";
        return $"M:{method.DeclaringType!.FullName}.{name}{list}";
    }

    private static string XmlTypeName(Type type)
    {
        if (type.IsByRef)
            return XmlTypeName(type.GetElementType()!) + "@";
        if (type.IsArray)
            return XmlTypeName(type.GetElementType()!) + "[]";
        if (type.IsGenericType)
        {
            var definition = type.GetGenericTypeDefinition().FullName!;
            return definition[..definition.IndexOf('`')] + "{" + string.Join(",", type.GetGenericArguments().Select(XmlTypeName)) + "}";
        }
        return type.FullName ?? type.Name;
    }

    private static string ParameterList(MethodBase method)
    {
        var nullability = new NullabilityInfoContext();
        return string.Join(", ", method.GetParameters().Select(p =>
        {
            var text = $"{TypeName(p.ParameterType, nullability.Create(p))} {p.Name}";
            if (p.HasDefaultValue)
                text += " = " + Literal(p.DefaultValue);
            return text;
        }));
    }

    private static string TypeName(Type type, NullabilityInfo? nullability = null)
    {
        var nullable = nullability?.ReadState == NullabilityState.Nullable && !type.IsValueType ? "?" : "";
        if (Nullable.GetUnderlyingType(type) is { } underlying)
            return TypeName(underlying) + "?";
        if (type.IsArray)
            return TypeName(type.GetElementType()!, nullability?.ElementType) + "[]" + nullable;
        if (type.IsGenericType)
        {
            var name = type.Name[..type.Name.IndexOf('`')];
            var arguments = type.GetGenericArguments().Select((t, i) => TypeName(t, nullability?.GenericTypeArguments.ElementAtOrDefault(i)));
            return $"{name}<{string.Join(", ", arguments)}>{nullable}";
        }
        return Keyword(type) + nullable;
    }

    private static string Keyword(Type type) => type.FullName switch
    {
        "System.String" => "string",
        "System.Boolean" => "bool",
        "System.Int32" => "int",
        "System.Int64" => "long",
        "System.Double" => "double",
        "System.Object" => "object",
        "System.Void" => "void",
        _ => type.Name,
    };

    private static string Literal(object? value) => value switch
    {
        null => "null",
        string s => $"\"{s}\"",
        bool b => b ? "true" : "false",
        double d when double.IsNaN(d) => "double.NaN",
        IFormattable f => f.ToString(null, System.Globalization.CultureInfo.InvariantCulture),
        _ => value.ToString() ?? "",
    };

    private static string Declaration(Type type)
    {
        var kind = KindName(type);
        var modifiers = type.IsInterface || type.IsEnum ? "" : type.IsAbstract && type.IsSealed ? "static " : type.IsSealed ? "sealed " : "";
        var keyword = kind switch
        {
            "interface" => "interface",
            "enum" => "enum",
            "record" => "record",
            _ => "class",
        };
        var bases = new List<string>();
        if (type.BaseType is { } baseType && baseType != typeof(object) && baseType != typeof(Enum) && baseType != typeof(ValueType))
            bases.Add(TypeName(baseType));
        bases.AddRange(type.GetInterfaces()
            .Where(i => i.Namespace == type.Namespace && !type.GetInterfaces().Any(o => o != i && i.IsAssignableFrom(o)))
            .Select(i => TypeName(i)));
        var flags = type.IsEnum && type.GetCustomAttribute<FlagsAttribute>() is not null ? "[Flags]\n" : "";
        return $"{flags}public {modifiers}{keyword} {DisplayName(type)}{(bases.Count > 0 ? " : " + string.Join(", ", bases) : "")}";
    }

    private static string KindName(Type type) =>
        type.IsInterface ? "interface"
        : type.IsEnum ? "enum"
        : IsRecord(type) ? "record"
        : typeof(Attribute).IsAssignableFrom(type) ? "attribute"
        : type.IsAbstract && type.IsSealed ? "static class"
        : "class";

    private static string DisplayName(Type type) => type.Name;

    private static string Plain(string name) => name.Contains('`') ? name[..name.IndexOf('`')] : name;

    private static bool IsRecord(Type type) => type.GetMethod("<Clone>$") is not null;

    private static bool IsCompilerGenerated(MemberInfo member) =>
        member.GetCustomAttribute<System.Runtime.CompilerServices.CompilerGeneratedAttribute>() is not null && member is MethodInfo;

    private static bool IsRecordPlumbing(Type type, MethodInfo method) =>
        IsRecord(type) && method.Name is "ToString" or "GetHashCode" or "Equals" or "Deconstruct" or "PrintMembers" or "<Clone>$" or "op_Equality" or "op_Inequality";

    private static string Cell(string text) => text.Replace("\r", "").Replace("\n\n", "<br>").Replace("\n", " ").Replace("|", "\\|");

    private static string Finish(StringBuilder sb) => sb.ToString().Replace("\r\n", "\n").TrimEnd('\n') + "\n";

    [GeneratedRegex(@"[ \t]+")]
    private static partial Regex Spaces();
}
