using System.Globalization;
using System.Text;
using AutoSettings.Core;
using AutoSettings.Core.Catalog;
using AutoSettings.Core.Engine;
using AutoSettings.Core.Model;
using AutoSettings.Core.Schema;

namespace AutoSettings.DocGen;

/// <summary>Builds the reference documentation from the component catalog.</summary>
public static class ReferenceGenerator
{
    private const string Banner = "<!-- Generated by AutoSettings.DocGen from the component catalog. Do not edit by hand: run `dotnet run --project src/AutoSettings.DocGen`. -->";

    /// <summary>Returns relative path → content (LF line endings) for every generated file.</summary>
    public static SortedDictionary<string, string> Generate()
    {
        var catalog = ComponentCatalog.Default;
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["index.md"] = Index(catalog),
            ["placeholders.md"] = PlaceholdersPage(),
            ["automations.schema.json"] = JsonSchemaGenerator.Generate(catalog),
        };
        foreach (var descriptor in catalog.All)
            files[$"{Folder(descriptor.Kind)}/{descriptor.Type}.md"] = Page(descriptor);
        return files;
    }

    private static string Folder(ComponentKind kind) => kind switch
    {
        ComponentKind.Trigger => "triggers",
        ComponentKind.Condition => "conditions",
        _ => "actions",
    };

    private static string Index(ComponentCatalog catalog)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Banner);
        sb.AppendLine();
        sb.AppendLine("# Reference");
        sb.AppendLine();
        sb.AppendLine("Every trigger, condition and action you can use in `automations.yaml`, with all fields and an example.");
        sb.AppendLine("See [the automation file format](../guide/automations.md) for how they fit together, and");
        sb.AppendLine("[placeholders](placeholders.md) for the `{{ ... }}` values you can use in text fields.");
        sb.AppendLine();
        sb.AppendLine("Editors that support JSON Schema (for example VS Code with the YAML extension) can use");
        sb.AppendLine("[`automations.schema.json`](automations.schema.json) for autocomplete and validation.");
        sb.AppendLine();

        foreach (var (kind, title, intro) in new[]
        {
            (ComponentKind.Trigger, "Triggers", "A trigger starts an automation. An automation runs when **any** of its triggers fires."),
            (ComponentKind.Condition, "Conditions", "Conditions are checked after a trigger fires. **All** of them must be true for the actions to run."),
            (ComponentKind.Action, "Actions", "Actions run in order. Actions marked *revertible* can be used in profiles and are undone when the profile is reverted."),
        })
        {
            sb.AppendLine($"## {title}");
            sb.AppendLine();
            sb.AppendLine(intro);
            foreach (var group in catalog.OfKind(kind).GroupBy(d => d.Category))
            {
                sb.AppendLine();
                sb.AppendLine($"### {group.Key}");
                sb.AppendLine();
                sb.AppendLine(kind == ComponentKind.Action ? "| Type | What it does | Revertible | Runs as |" : "| Type | What it does | Available in |");
                sb.AppendLine(kind == ComponentKind.Action ? "|---|---|---|---|" : "|---|---|---|");
                foreach (var d in group)
                {
                    var link = $"[`{d.Type}`]({Folder(kind)}/{d.Type}.md)";
                    sb.AppendLine(kind == ComponentKind.Action
                        ? $"| {link} | {Cell(d.Description)} | {(d.Revertible ? "yes" : "no")} | {RunsAs(d)} |"
                        : $"| {link} | {Cell(d.Description)} | {AvailableIn(d)} |");
                }
            }
            sb.AppendLine();
        }
        return Finish(sb);
    }

    private static string Page(ComponentDescriptor d)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Banner);
        sb.AppendLine();
        sb.AppendLine($"# {d.Title} (`{d.Type}`)");
        sb.AppendLine();
        var facts = new List<string> { $"**Kind:** {d.Kind.ToString().ToLowerInvariant()}", $"**Category:** {d.Category}" };
        if (d.Kind == ComponentKind.Action)
        {
            facts.Add($"**Runs as:** {RunsAs(d)}");
            facts.Add($"**Revertible:** {(d.Revertible ? "yes" : "no")}");
        }
        else
        {
            facts.Add($"**Available in:** {AvailableIn(d)}");
        }
        sb.AppendLine(string.Join(" · ", facts));
        sb.AppendLine();
        sb.AppendLine(d.Description);
        sb.AppendLine();

        sb.AppendLine("## Fields");
        sb.AppendLine();
        if (d.Fields.Count == 0)
        {
            sb.AppendLine("This " + d.Kind.ToString().ToLowerInvariant() + " has no fields.");
        }
        else
        {
            sb.AppendLine("| Field | Type | Required | Default | Description |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var f in d.Fields)
            {
                var description = f.Description + (f.SupportsPlaceholders && d.Kind == ComponentKind.Action ? " Supports [placeholders](../placeholders.md)." : "");
                sb.AppendLine($"| `{f.Name}` | {TypeName(f)} | {(f.Required ? "yes" : "no")} | {DefaultText(f)} | {Cell(description)} |");
            }
        }
        sb.AppendLine();

        if (d.Example is { } example)
        {
            sb.AppendLine("## Example");
            sb.AppendLine();
            var section = d.Kind switch
            {
                ComponentKind.Trigger => "triggers",
                ComponentKind.Condition => "conditions",
                _ => "actions",
            };
            sb.AppendLine("```yaml");
            sb.AppendLine($"{section}:");
            var lines = example.Replace("\r\n", "\n").TrimEnd().Split('\n');
            sb.AppendLine("  - " + lines[0]);
            foreach (var line in lines.Skip(1))
                sb.AppendLine("    " + line);
            sb.AppendLine("```");
            sb.AppendLine();
        }

        if (d.Kind == ComponentKind.Action && d.Revertible)
        {
            sb.AppendLine("## In profiles");
            sb.AppendLine();
            sb.AppendLine("When this action is part of a [profile](../../guide/profiles.md), the current value is saved before it runs and");
            sb.AppendLine("restored when the profile is reverted." + (d.KeyFields.Count > 0
                ? $" Two actions of this type change the same setting when their {string.Join(" and ", d.KeyFields.Select(k => $"`{k}`"))} {(d.KeyFields.Count == 1 ? "is" : "are")} the same."
                : ""));
            sb.AppendLine();
        }

        if (d.Notes is { } notes)
        {
            sb.AppendLine("## Notes");
            sb.AppendLine();
            sb.AppendLine(notes);
            sb.AppendLine();
        }

        sb.AppendLine("[All triggers, conditions and actions](../index.md)");
        return Finish(sb);
    }

    private static string PlaceholdersPage()
    {
        var sb = new StringBuilder();
        sb.AppendLine(Banner);
        sb.AppendLine();
        sb.AppendLine("# Placeholders");
        sb.AppendLine();
        sb.AppendLine("Text fields of actions (messages, commands, paths, arguments, ...) can contain placeholders that are");
        sb.AppendLine("replaced with details of the event that started the automation. Write them as `{{ name }}`.");
        sb.AppendLine("Placeholders that do not apply to the event (for example `{{ app }}` for a sign-in) become empty text;");
        sb.AppendLine("unknown names are left unchanged.");
        sb.AppendLine();
        sb.AppendLine("| Placeholder | Value |");
        sb.AppendLine("|---|---|");
        foreach (var (name, description) in Placeholders.All)
            sb.AppendLine($"| `{{{{ {name} }}}}` | {Cell(description)} |");
        sb.AppendLine();
        sb.AppendLine("## Example");
        sb.AppendLine();
        sb.AppendLine("```yaml");
        sb.AppendLine("actions:");
        sb.AppendLine("  - type: notify");
        sb.AppendLine("    message: \"Welcome back, {{ user }}! It is {{ time }}.\"");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("> In YAML, a value that **starts** with `{{` must be quoted, otherwise it is read as a map.");
        sb.AppendLine();
        sb.AppendLine("## Scripts");
        sb.AppendLine();
        sb.AppendLine("Placeholders are **not** replaced inside `command.run` scripts: window titles and file names are chosen by other");
        sb.AppendLine("programs, and pasting them into code could run unintended commands. Instead, every value is passed to the script");
        sb.AppendLine("as an environment variable named `AUTOSETTINGS_` + the placeholder name in capitals, with dots replaced by underscores:");
        sb.AppendLine();
        sb.AppendLine("| Placeholder | PowerShell | cmd |");
        sb.AppendLine("|---|---|---|");
        foreach (var (name, _) in Placeholders.All)
        {
            var variable = "AUTOSETTINGS_" + name.ToUpperInvariant().Replace('.', '_');
            sb.AppendLine($"| `{{{{ {name} }}}}` | `$env:{variable}` | `%{variable}%` |");
        }
        sb.AppendLine();
        sb.AppendLine("```yaml");
        sb.AppendLine("actions:");
        sb.AppendLine("  - type: command.run");
        sb.AppendLine("    command: Add-Content \"$env:TEMP\\apps.log\" \"$env:AUTOSETTINGS_NOW started $env:AUTOSETTINGS_APP\"");
        sb.AppendLine("```");
        return Finish(sb);
    }

    private static string TypeName(FieldDescriptor f)
    {
        var name = f.Type switch
        {
            FieldType.String => "text",
            FieldType.Multiline => "text (multi-line)",
            FieldType.Path => "file path",
            FieldType.Integer => "whole number",
            FieldType.Number => "number",
            FieldType.Boolean => "true / false",
            FieldType.Enum => "one of: " + string.Join(", ", (f.AllowedValues ?? []).Select(v => $"`{v}`")),
            FieldType.Duration => "duration (`30s`, `5m`, `1h30m`)",
            FieldType.Time => "time of day (`HH:mm`)",
            FieldType.StringList => f.AllowedValues is { Count: > 0 } values
                ? "list of: " + string.Join(", ", values.Select(v => $"`{v}`"))
                : "text or list of text",
            FieldType.AppList => "app or list of apps",
            FieldType.UserList => "user or list of users",
            FieldType.ConditionList => "list of conditions",
            _ => f.Type.ToString(),
        };
        if (f.Minimum is not null || f.Maximum is not null)
        {
            var min = f.Minimum?.ToString(CultureInfo.InvariantCulture);
            var max = f.Maximum?.ToString(CultureInfo.InvariantCulture);
            name += min is not null && max is not null ? $" ({min}–{max})" : min is not null ? $" (≥ {min})" : $" (≤ {max})";
        }
        return name;
    }

    private static string DefaultText(FieldDescriptor f) =>
        f.Default is null ? "" : $"`{ValueConverter.ToText(f.Default)}`";

    private static string RunsAs(ComponentDescriptor d) =>
        d.RunsAsResolver is not null
            ? "depends on the fields (see below)"
            : d.RunsAs == ExecutionScope.Machine ? "SYSTEM (machine automations only)" : "the signed-in user";

    private static string AvailableIn(ComponentDescriptor d) => d.AvailableIn switch
    {
        ScopeSupport.User => "personal automations",
        ScopeSupport.Machine => "machine automations",
        _ => "personal and machine automations",
    };

    private static string Cell(string text) => text.Replace("|", "\\|").Replace("\r", "").Replace("\n", " ");

    private static string Finish(StringBuilder sb) => sb.ToString().Replace("\r\n", "\n").TrimEnd() + "\n";
}
