"""Source of the agent's UI strings (English + Turkish). Run: python3 tools/strings.py
Generates src/AutoSettings.Agent/Resources/Strings.resx and Strings.tr.resx (and the catalog files)."""
from xml.sax.saxutils import escape
import os

S = {
 "Account": ("Account", "Hesap"),
 "Active": ("Active", "Etkin"),
 "ActiveProfiles": ("Active profiles: {0}", "Etkin profiller: {0}"),
 "ActiveReverts": ("Active, reverts {0}", "Etkin, geri alınır: {0}"),
 "Activity": ("Activity", "Etkinlik"),
 "ActivityHint": ("What happened and why, newest first. It also explains why an automation did not run.", "Ne oldu ve neden, en yenisi üstte. Bir otomasyonun neden çalışmadığını da açıklar."),
 "AddAction": ("+ Add action", "+ Eylem ekle"),
 "AddCondition": ("+ Add condition", "+ Koşul ekle"),
 "AddTemplate": ("Add", "Ekle"),
 "AddTrigger": ("+ Add trigger", "+ Tetikleyici ekle"),
 "Always": ("always", "her zaman"),
 "AndSeparator": (" and ", " ve "),
 "App": ("App", "Uygulama"),
 "Appearance": ("Appearance", "Görünüm"),
 "Apply": ("Apply", "Uygula"),
 "Automations": ("Automations", "Otomasyonlar"),
 "AutomationsHint": ("WHEN a trigger happens, IF all conditions are true, THEN the actions run in order. Double-click to edit.", "Bir tetikleyici gerçekleştiğinde, tüm koşullar doğruysa eylemler sırayla çalışır. Düzenlemek için çift tıklayın."),
 "AutomationsOn": ("{0} of {1} automations on", "{1} otomasyondan {0} açık"),
 "Browse": ("Browse…", "Gözat…"),
 "Cancel": ("Cancel", "İptal"),
 "Clear": ("Clear", "Temizle"),
 "Connected": ("connected", "bağlı"),
 "Cooldown": ("Cooldown", "Bekleme süresi"),
 "CouldNotStart": ("{0} could not start:\n\n{1}", "{0} başlatılamadı:\n\n{1}"),
 "Dark": ("Dark", "Koyu"),
 "DefaultValue": ("Default: {0}", "Varsayılan: {0}"),
 "Delete": ("Delete", "Sil"),
 "DeleteQuestion": ("Delete {0} item(s)?", "{0} öğe silinsin mi?"),
 "Description": ("Description", "Açıklama"),
 "DiscardChanges": ("Discard changes", "Değişiklikleri at"),
 "DiscardQuestion": ("You have unsaved changes. Close anyway?", "Kaydedilmemiş değişiklikler var. Yine de kapatılsın mı?"),
 "Documentation": ("Documentation", "Belgeler"),
 "DryRun": ("Dry run: log actions instead of running them", "Deneme modu: eylemleri çalıştırmak yerine günlüğe yaz"),
 "DryRunSuffix": (" (dry run)", " (deneme modu)"),
 "Duplicate": ("Duplicate", "Çoğalt"),
 "Edit": ("Edit", "Düzenle"),
 "EditAutomationTitle": ("Automation: {0}", "Otomasyon: {0}"),
 "EditAutomationsFile": ("Edit automations file", "Otomasyon dosyasını düzenle"),
 "EditProfileTitle": ("Profile: {0}", "Profil: {0}"),
 "EditWholeFile": ("Edit whole file", "Tüm dosyayı düzenle"),
 "Enabled": ("Enabled", "Etkin"),
 "ErrorsKeepPrevious": ("{0} error(s), the previous version is still running", "{0} hata, önceki sürüm çalışmaya devam ediyor"),
 "Exit": ("Exit", "Çıkış"),
 "Export": ("Export", "Dışa aktar"),
 "FileEditorHint": ("Edit the whole file. Comments and formatting are kept. Press Ctrl+Space for suggestions; hover for help.", "Tüm dosyayı düzenleyin. Yorumlar ve biçim korunur. Öneriler için Ctrl+Boşluk; yardım için fareyle üzerine gelin."),
 "FileErrorsTitle": ("{0}: automations.yaml has errors", "{0}: automations.yaml dosyasında hatalar var"),
 "FileHasErrors": ("automations.yaml has errors", "automations.yaml dosyasında hatalar var"),
 "FixFileFirst": ("automations.yaml has errors. Fix them with 'Edit whole file' before using the editor.", "automations.yaml dosyasında hatalar var. Düzenleyiciyi kullanmadan önce 'Tüm dosyayı düzenle' ile düzeltin."),
 "FixYamlFirst": ("Fix the errors in the YAML first.", "Önce YAML içindeki hataları düzeltin."),
 "FollowWindows": ("Same as Windows", "Windows ile aynı"),
 "For15Minutes": ("For 15 minutes", "15 dakika"),
 "For1Hour": ("For 1 hour", "1 saat"),
 "Found": ("Found", "Kaynak"),
 "HasErrors": ("There are errors.", "Hatalar var."),
 "Id": ("Id", "Kimlik"),
 "If": ("If", "Eğer"),
 "IfHint": ("All of these must be true. Leave empty to always run.", "Bunların hepsi doğru olmalı. Her zaman çalışması için boş bırakın."),
 "IfSection": ("If", "Eğer"),
 "Import": ("Import", "İçe aktar"),
 "ImportInvalid": ("The file cannot be imported:", "Dosya içe aktarılamıyor:"),
 "Imported": ("Imported {0} automation(s) and {1} profile(s).", "{0} otomasyon ve {1} profil içe aktarıldı."),
 "Language": ("Language", "Dil"),
 "Light": ("Light", "Açık"),
 "LocalAccount": ("Local account", "Yerel hesap"),
 "MachineActivity": ("Machine (service) activity", "Makine (hizmet) etkinliği"),
 "MoveDown": ("Move down", "Aşağı taşı"),
 "MoveUp": ("Move up", "Yukarı taşı"),
 "MyActivity": ("My activity", "Etkinliğim"),
 "Name": ("Name", "Ad"),
 "New": ("New", "Yeni"),
 "NewAutomationName": ("New automation", "Yeni otomasyon"),
 "NewProfileName": ("New profile", "Yeni profil"),
 "NoMachineActivity": ("No machine activity yet.", "Henüz makine etkinliği yok."),
 "NoProfilesYet": ("No profiles yet", "Henüz profil yok"),
 "NotConnectedLong": ("not connected (sign-in and lock detection need the service)", "bağlı değil (oturum açma ve kilit algılama için hizmet gerekir)"),
 "NotSaved": ("Not saved:", "Kaydedilmedi:"),
 "NotSavedFixErrors": ("Not saved: fix the errors first.", "Kaydedilmedi: önce hataları düzeltin."),
 "NotSet": ("(not set)", "(ayarlanmadı)"),
 "Off": ("Off", "Kapalı"),
 "On": ("On", "Açık"),
 "OpenAutomationsFolder": ("Open automations folder", "Otomasyon klasörünü aç"),
 "OpenInOtherEditor": ("Open in another editor", "Başka düzenleyicide aç"),
 "OpenLogFolder": ("Open log folder", "Günlük klasörünü aç"),
 "OpenProduct": ("Open {0}", "{0} aç"),
 "OrSeparator": (" or ", " veya "),
 "PathColumn": ("Path", "Yol"),
 "PauseAutomations": ("Pause automations", "Otomasyonları duraklat"),
 "PauseOneHour": ("Pause for 1 hour", "1 saat duraklat"),
 "Paused": ("Paused", "Duraklatıldı"),
 "PausedUntil": ("Paused until {0}", "{0} saatine kadar duraklatıldı"),
 "PickApp": ("Pick app…", "Uygulama seç…"),
 "PickAppTitle": ("Choose an app", "Uygulama seçin"),
 "PickUser": ("Pick user…", "Kullanıcı seç…"),
 "PickUserTitle": ("Choose a user", "Kullanıcı seçin"),
 "Priority": ("Priority", "Öncelik"),
 "Profiles": ("Profiles", "Profiller"),
 "ProfilesHint": ("A profile is a set of settings that is applied together and undone together.", "Profil, birlikte uygulanan ve birlikte geri alınan bir ayar grubudur."),
 "ReloadAutomations": ("Reload automations", "Otomasyonları yeniden yükle"),
 "Remove": ("Remove", "Kaldır"),
 "RestartForLanguage": ("Restart AutoSettings (tray icon → Exit, then start it again) to change the language.", "Dili değiştirmek için AutoSettings'i yeniden başlatın (tepsi simgesi → Çıkış, sonra tekrar başlatın)."),
 "Resume": ("Resume", "Devam et"),
 "ResumeAutomations": ("Resume automations", "Otomasyonlara devam et"),
 "Revert": ("Revert", "Geri al"),
 "RewriteNotice": ("The editor saves automations.yaml in a standard format. Comments and custom formatting in the file are not kept. Use 'Edit whole file' if you want to keep them.\n\nContinue?", "Düzenleyici automations.yaml dosyasını standart biçimde kaydeder. Dosyadaki yorumlar ve özel biçimlendirme korunmaz. Bunları korumak istiyorsanız 'Tüm dosyayı düzenle'yi kullanın.\n\nDevam edilsin mi?"),
 "RunIgnoringConditions": ("Run, ignoring conditions", "Koşulları yok sayarak çalıştır"),
 "RunNow": ("Run now", "Şimdi çalıştır"),
 "Running": ("running", "çalışıyor"),
 "Save": ("Save", "Kaydet"),
 "SavedAt": ("Saved at {0}.", "{0} saatinde kaydedildi."),
 "Search": ("Search", "Ara"),
 "Select": ("Select", "Seç"),
 "ServiceConnected": ("Service connected", "Hizmet bağlı"),
 "ServiceNotConnected": ("Service not connected", "Hizmet bağlı değil"),
 "Settings": ("Settings", "Ayarlar"),
 "SignedIn": ("Signed in", "Oturum açık"),
 "StartMenu": ("Start menu", "Başlat menüsü"),
 "Status": ("Status", "Durum"),
 "StatusAppDetection": ("App start/close detection: {0}", "Uygulama başlatma/kapatma algılama: {0}"),
 "StatusEngine": ("Automations: {0}{1}", "Otomasyonlar: {0}{1}"),
 "StatusFile": ("Automations file: {0}", "Otomasyon dosyası: {0}"),
 "StatusFocus": ("Focused app: {0}", "Odaktaki uygulama: {0}"),
 "StatusLastLoad": ("Last load: {0}, {1} warning(s)", "Son yükleme: {0}, {1} uyarı"),
 "StatusLogs": ("Logs: {0}", "Günlükler: {0}"),
 "StatusMachineFile": ("Machine automations: {0} (administrators only)", "Makine otomasyonları: {0} (yalnızca yöneticiler)"),
 "StatusService": ("Service: {0}", "Hizmet: {0}"),
 "StatusSuspended": ("Suspended by the loop guard: {0} (save the file to resume)", "Döngü koruması tarafından askıya alındı: {0} (devam etmek için dosyayı kaydedin)"),
 "StatusUser": ("Signed in as {0} (session {1})", "Oturum: {0} (oturum {1})"),
 "TemplateAdded": ("'{0}' was added: {1} automation(s) and {2} profile(s). You can edit them now.", "'{0}' eklendi: {1} otomasyon ve {2} profil. Şimdi düzenleyebilirsiniz."),
 "Templates": ("Templates", "Şablonlar"),
 "TemplatesHint": ("Ready-made automations. Add one, then adjust it to your apps and devices.", "Hazır otomasyonlar. Birini ekleyin, sonra uygulamalarınıza ve cihazlarınıza göre ayarlayın."),
 "Test": ("Test", "Dene"),
 "TestFinished": ("Test finished. See the Activity page for details.", "Deneme bitti. Ayrıntılar için Etkinlik sayfasına bakın."),
 "TestStarted": ("Running the actions…", "Eylemler çalıştırılıyor…"),
 "Testing": ("Testing", "Deneme"),
 "Theme": ("Theme", "Tema"),
 "Then": ("Then", "O zaman"),
 "ThenHint": ("These run in order.", "Bunlar sırayla çalışır."),
 "ThenSection": ("Then", "O zaman"),
 "Time": ("Time", "Saat"),
 "UnknownType": ("Unknown type '{0}'. Edit it in the YAML view.", "Bilinmeyen tür '{0}'. YAML görünümünde düzenleyin."),
 "UnsavedChanges": ("Unsaved changes", "Kaydedilmemiş değişiklikler"),
 "UntilIResume": ("Until I resume", "Ben devam ettirene kadar"),
 "UseDomainName": ("Use DOMAIN\\name", "ETKİ ALANI\\ad kullan"),
 "UseFullPath": ("Use the full path instead of the file name", "Dosya adı yerine tam yolu kullan"),
 "User": ("User", "Kullanıcı"),
 "Visual": ("Visual", "Görsel"),
 "WhatHappened": ("What happened", "Ne oldu"),
 "When": ("When", "Ne zaman"),
 "WhenHint": ("Any of these starts the automation.", "Bunlardan herhangi biri otomasyonu başlatır."),
 "WhenSection": ("When", "Ne zaman"),
}

# Turkish titles for the catalog (English titles come from the catalog itself).
CATALOG_TR = {
 "Category.Computer_and_sign-in": "Bilgisayar ve oturum açma",
 "Category.Apps": "Uygulamalar",
 "Category.Logic": "Mantık",
 "Category.Context": "Bağlam",
 "Category.Device": "Cihaz",
 "Category.Flow": "Akış",
 "Category.Personalization": "Kişiselleştirme",
 "Category.Display": "Ekran",
 "Category.Power": "Güç",
 "Category.Audio": "Ses",
 "Category.Network_and_devices": "Ağ ve cihazlar",
 "Category.Apps_and_scripts": "Uygulamalar ve betikler",
 "Category.Notifications": "Bildirimler",
 "Category.Advanced": "Gelişmiş",
 "Trigger.boot": "Bilgisayar başladı",
 "Trigger.logon": "Kullanıcı oturum açtı",
 "Trigger.logoff": "Kullanıcı oturumu kapattı",
 "Trigger.lock": "Ekran kilitlendi",
 "Trigger.unlock": "Ekran kilidi açıldı",
 "Trigger.app_started": "Uygulama başladı",
 "Trigger.app_closed": "Uygulama kapandı",
 "Trigger.app_focused": "Uygulama odaklandı",
 "Trigger.app_unfocused": "Uygulama odaktan çıktı",
 "Condition.and": "Hepsi",
 "Condition.or": "Herhangi biri",
 "Condition.not": "Hiçbiri",
 "Condition.user": "Kullanıcı",
 "Condition.time": "Saat / gün",
 "Condition.power_source": "Güç kaynağı",
 "Condition.battery": "Pil seviyesi",
 "Condition.app_running": "Uygulama çalışıyor",
 "Condition.app_focused": "Uygulama odakta",
 "Condition.fullscreen": "Tam ekran uygulama etkin",
 "Condition.wifi": "Wi‑Fi ağı",
 "Condition.monitor_count": "Monitör sayısı",
 "Condition.profile_active": "Profil etkin",
 "Action.profile.apply": "Profili uygula",
 "Action.profile.revert": "Profili geri al",
 "Action.delay": "Bekle",
 "Action.theme.mode": "Açık / koyu mod",
 "Action.theme.transparency": "Saydamlık efektleri",
 "Action.theme.accent_color": "Vurgu rengi",
 "Action.wallpaper.set": "Duvar kağıdını ayarla",
 "Action.taskbar.autohide": "Görev çubuğunu otomatik gizle",
 "Action.display.brightness": "Ekran parlaklığı",
 "Action.display.resolution": "Çözünürlük / yenileme hızı",
 "Action.display.hdr": "HDR",
 "Action.display.primary": "Ana ekran",
 "Action.display.scaling": "Ekran ölçeklendirme",
 "Action.display.night_light": "Gece ışığı",
 "Action.power.plan": "Güç planı",
 "Action.power.mode": "Güç modu",
 "Action.power.screen_timeout": "Ekranı kapatma süresi",
 "Action.power.sleep_timeout": "Uyku süresi",
 "Action.audio.volume": "Ses düzeyi",
 "Action.audio.mute": "Sessiz / sesi aç",
 "Action.audio.default_device": "Varsayılan ses cihazı",
 "Action.radio.set": "Wi‑Fi / Bluetooth aç veya kapat",
 "Action.radio.airplane_mode": "Uçak modu",
 "Action.mouse.speed": "Fare işaretçisi hızı",
 "Action.keyboard.layout": "Klavye düzeni",
 "Action.notifications.banners": "Bildirim afişleri",
 "Action.notifications.do_not_disturb": "Rahatsız etmeyin",
 "Action.app.launch": "Uygulama başlat",
 "Action.app.close": "Uygulamayı kapat",
 "Action.command.run": "Komut / betik çalıştır",
 "Action.notify": "Bildirim göster",
 "Action.open": "URL / ayar sayfası aç",
 "Action.settings.open": "Windows Ayarları sayfasını aç",
 "Action.registry.set": "Kayıt defteri değeri ayarla",
 "Action.service.control": "Hizmeti başlat / durdur",
}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/strings.py. Edit that file, then run: python3 tools/strings.py -->
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""

def write(path, entries):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        for key in sorted(entries):
            f.write(f'  <data name="{escape(key)}" xml:space="preserve"><value>{escape(entries[key])}</value></data>\n')
        f.write("</root>\n")

root = os.path.join(os.path.dirname(__file__), "..", "src", "AutoSettings.Agent", "Resources")
os.makedirs(root, exist_ok=True)
write(os.path.join(root, "Strings.resx"), {k: v[0] for k, v in S.items()})
write(os.path.join(root, "Strings.tr.resx"), {k: v[1] for k, v in S.items()})
write(os.path.join(root, "Catalog.resx"), {})
write(os.path.join(root, "Catalog.tr.resx"), CATALOG_TR)
print(f"{len(S)} UI strings, {len(CATALOG_TR)} catalog strings")
